jetbot_3:
  controller_manager:
    ros__parameters:
      update_rate: 100
      use_sim_time: true

      diff_controller:
        type: diff_drive_controller/DiffDriveController

      joint_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  diff_controller:
    ros__parameters:

      publish_rate: 100.0
 
      base_frame_id: base_link

      left_wheel_names: ['leftWheel_joint']
      right_wheel_names: ['rightWheel_joint']
      wheel_separation: 0.1863
      wheel_radius: 0.0325

      use_stamped_vel: false


  # joint_broadcaster:
  #   ros__parameters: